services:
  nginx:
    image: nginx:latest
    container_name: nginx
    profiles:
      - prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/data/letsencrypt
    depends_on:
      api:
        condition: service_started
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    profiles:
      - prod
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/ssl-data:/data/letsencrypt
    depends_on:
      nginx:
        condition: service_started
    entrypoint: >
      /bin/sh -c "
      if [ ! -d /etc/letsencrypt/live/hack.fadegor05.ru ]; then
        certbot certonly --webroot --webroot-path=/data/letsencrypt -d hack.fadegor05.ru --agree-tos --register-unsafely-without-email;
        nginx -s reload;
      fi;
      trap exit TERM;
      while :; do sleep 6h & wait $${!}; certbot renew; done"
    restart: always
